### ISSUE TITLE
ready to publish!

### ISSUE THREAD

**Issue by shyamgupta196** [shyamgupta196/Audio-Sentiment-Classification#1]
meets MH:V3 guidelines

**Comment by johanneskiesel** [comment]
- [x] Missing ORCID (https://orcid.org/0009-0003-4639-5618)

![Image](https://github.com/user-attachments/assets/1c1001fe-8cae-4d80-92db-26b735408226)

**Comment by shyamgupta196** [comment]
The ORCID is now visible.

**Comment by shyamgupta196** [comment]
Should I close this and move it to awaiting publication?

**Comment by johanneskiesel** [comment]
yes, sounds good to me

**Comment by johanneskiesel** [comment]
`pip install -r binder/requirements.txt` needs to be an own cell. I can’t execute it in the interactive environment. 
 
I’m not sure how to install from a requirements file in Jupyter.  

Can not start this tutorial :(

(for some reason, I can't reopen this issue)

**Comment by shyamgupta196** [comment]
I think you have to install it from the root of the directory. if you try to install it from binder, it wont work. I hope that helps.

**Comment by johanneskiesel** [comment]
Can you please make it so that I just have to execute the cell in the interactive environment?

**Comment by shyamgupta196** [comment]
Hello @johanneskiesel  I have fixed the issue. Please check it.

**Comment by johanneskiesel** [comment]
I tried with the newest commit ID, and the intall process starts now (thanks!), but fails ( :( )
https://mybinder.org/v2/gh/shyamgupta196/Audio-Sentiment-Classification/1ac927e6c6cbc0a91c975c986d1bc0f5b5751aa0

![Image](https://github.com/user-attachments/assets/4b8104b2-94df-4faf-8dec-07186bc08717)

**Comment by shyamgupta196** [comment]
Solved the error, please review it. I will be moving this to awaiting publication now.

**Comment by FlxVctr** [comment]
Second review:

Very interesting tutorial and nice example, especially for me, as I'd like to work more with audio, thanks for that! However, given that this will be one of the first tutorials that will set the tone and quality benchmark for everything following, I still see work to do.

**technical:**
- [ ] mybinder.org not building, please refer to #2 for a possible solution
- [x] for local execution, the `ipykernel` package is required in the (dev) requirements (assuming some Jupyter Notebook editor is already available, e.g. VS Code or Jupyterlab)
- [x] doesn't work with Python 3.13, please note the required Python version (3.11 seems to work)
- [ ] Cell 5 in the notebook throws NotADirectory Error on macOS. I see that you tried to solve that with a comment (and uncommenting lets the whole notebook run fine) but I'd rather use one of the solutions here: https://stackoverflow.com/questions/7099290/how-to-ignore-hidden-files-using-os-listdir
- [x] It'd be nice if the datasets would be downloaded via code in a cell (e.g. with requests or urllib, we cannot assume that the user has wget or curl available, unfortunately. You could still offer a line of bash for those though) and unpacked into the right folder (with a warning about diskspace!). But just some info on where to unpack them is necessary in any case. Also the info that the full dataset should be downloaded is a bit hidden. I overlooked it at first.

**content:**

- [ ] README and tutorial notebook have discrepancies, e.g.,
    - [x] accuracy numbers of output in notebook, notebook text and README don't match (and will vary from run to run depending on parameters, machine, sunspots, and dark matter I guess)
    - [ ] unclear to me, why the README is that long if it mostly mirrors the notebook anyway
    - [x] why link to notebook on Github and not to Binder directly? (or just take the relative path, "Follow the notebook in [GITHUB](https://github.com/shyamgupta196/Audio-Sentiment-Classification/blob/main/audio-sentiment-classification.ipynb)" sounds odd within this context, i.e., the repos content should be independent from the git hoster)
- [x] under use cases, the tutorial gets a bit 'oversold' (e.g. "this notebook is a powerful tool" is a bit hyperbole. It's rather a 'demonstration' as mentioned in the objectives. I would rather try to manage expectations here, than 'sell' this like a course on Coursera or similar.
- [ ] comments in ipynb need some proof reading (e.g. "# as their are 20 different actors in our previous directory we need to extract files for each actor."). There are also some comments left that are irrelevant to the end user (e.g. about what did not work)
- [ ] "basic familiarity with Python and machine learning concepts will be helpful." I'd argue that both are necessary not only helpful – again expectation management. In general I'd recommend to find a test subject from CSS and let them go through the tutorial while thinking aloud (without answering their questions). I think a few more explanations here and there might be necessary. I especially miss some motivation/reasoning for the choices in Cell 16. I get that there's also the need to be concise, but a short explainer, why those choices have been made would be helpful (maybe also with links to external resources that explain them more in-depth)

**Comment by FlxVctr** [comment]
Ah, forgot: link/badge to guidelines is outdated (nice touch though)

**Comment by shyamgupta196** [comment]
I made a commit, 
1. cell 5 - yeah the hidden files are annoying. but I have added your stackoverflow recommendation. Thank you.
2. I made available a sample of the original dataset since uploading the whole dataset takes a lot of space on GitHub, unfortunately there is no curl or wget` command. I would make more clear for the user to understand that we are working with a sample data in this tutorial.
3. I made the readme different than notebook for the user who comes to methodshub and sees Audio-Sentiment-Analysis and clicks on the method, so I thought why not make a readme for the user to read and learn and be excited from reading the readme so if they really wanted to experiment, they have an option of going through notebook from GitHub link. 
- The readme and notebook accuracy doesn't match, because of the epochs I trained and I mentioned it in the both.
- since this tutorial uses methods of deep learning , I wanted it to as descriptive as possible for the beginner user. `I can trim it down if you suggest`
- I will remove the GitHub link to notebook.
4. I see your point of overselling this tutorial. now I cant ignore it haha, I corrected the words.
5. we do have 20 actors in our directory but since I only uploaded a sample of dataset it might not match. `should I keep the original one or sampled data one?`
6. can you please attach a screenshot of cell 16.
7. Thank you, I have updated the badge links tooo
